### ISSUE TITLE
Actual model files?

### ISSUE THREAD

**Issue by Zeit42** [leferrad/tensorflow-mobilenet#1]
Dumb question but where are the actual model files? All I see are label.s

**Comment by leferrad** [comment]
You can see in the following script an example of downloading a model file to use it: https://github.com/leferrad/tensorflow-mobilenet/blob/master/scripts/freeze_graph.py#L52-L57

Notice that this repo is only working with Python2, and it is actually deprecated, so just take it as an example of usage, not for production purposes.
